### ISSUE TITLE
Take ECC Public Key out of JWT Token

### ISSUE THREAD

**Issue by WingZer0o** [Cryptographic-API-Services/cas-api#56]
Should be stored in the database and populated in cache. If it doesn't exist in cache it should pull from database.

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the GetSuccessfulLogins method to use Redis caching. It now checks the cache first before querying the database, and stores the results in the cache if they're not already present.

You can review changes in this commit: https://github.com/lattaai13/Cryptographic-API-Services-cas-api-56/commit/99fa8028ba9627a0647bec22898e69a9a782924c.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by WingZer0o** [comment]
@lattaai13 Thanks for the attempt here with your tool, if I reading this correctly this was done by AI?

I was actually referring to the ECC signed JWT token that is being signed and created on the server, this implementation crosses  into another repo at https://github.com/Cryptographic-API-Services/cas-dotnet-helpers where the JWT class lives that actually makes this token. Currently I am storing the ECC token inside a claim of the token and it should just be cached in Redis and be queried from the database if it doesn't exist in cache.

**Comment by WingZer0o** [comment]
@lattaai13 I submitted a PR for this issue here and merged the changes into the main repository. https://github.com/Cryptographic-API-Services/cas-api/pull/58

If your model takes feedback, it can siphon it from this issue post.

Feel free to try again on the repo. Cool project!

I am going to close this issue.
